# Cronの設定情報
cron:
  # CSVをアップロードするスクリプトを定期実行する
  upload_csv: 0 5 * * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/upload_csv.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/upload_csv.log 2>&1
  # Nexmonを起動し，CSIを収集するスクリプトを定期実行する
  exec_nexmon: */15 * * * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/exec_nexmon.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/exec_nexmon.log 2>&1
  # pcapをダウンロードするスクリプトを定期実行する
  get_pcap: 0 3 * * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/get_pcap.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/get_pcap.log 2>&1