# Cronの設定情報
cron:
  # 設定ファイルを更新するスクリプトを定期実行する
  update_config: 0 0 1 * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/update_config.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/cron-update_config.log 2>&1
  # Nexmonを起動し，CSIを収集するスクリプトを定期実行する
  exec_nexmon: */15 * * * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/exec_nexmon.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/cron-exec_nexmon.log 2>&1
  # pcapをダウンロードするスクリプトを定期実行する
  get_pcap: 0 2 * * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/get_pcap.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/cron-get_pcap.log 2>&1
  # CSVをアップロードするスクリプトを定期実行する
  upload_pcap: 0 3 * * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/upload_pcap.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/cron-upload_pcap.log 2>&1
  # リモートのpcapファイル削除を定期実行する
  delete_remote_pcap: 0 4 * * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/delete_pcap.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/cron-delete_pcap.log 2>&1
  # pcapファイルの削除を定期実行する
  delete_pcap: 0 4 * * * find /home/pi/minelab-agri-platform/minelab-iot-gateway/pcap -type f -name "*.pcap" -delete