# Cronの設定情報
cron:
  # 設定ファイルを更新するスクリプトを定期実行する
  update_config: 0 0 1 * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/update_config.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/update_config.log 2>&1
  # Nexmonを起動し，CSIを収集するスクリプトを定期実行する
  exec_nexmon: */15 * * * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/exec_nexmon.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/exec_nexmon.log 2>&1
  # pcapをダウンロードするスクリプトを定期実行する
  get_pcap: 0 2 * * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/get_pcap.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/get_pcap.log 2>&1
  # pcapを復号するスクリプトを定期実行する
  get_pcap: 0 3 * * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/decode_pcap2csv.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/decode_pcap2csv.log 2>&1
  # pcapファイルの削除を定期実行する
  delete_pcap: 0 4 * * * find /home/pi/minelab-agri-platform/minelab-iot-gateway/pcap -type f -name "*.pcap" -delete
  # 前処理を実行するスクリプトを定期実行する
  get_pcap: 0 5 * * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/preprocess_csv.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/preprocess_csv.log 2>&1
  # CSVをアップロードするスクリプトを定期実行する
  upload_csv: 0 6 * * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/upload_csv.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/upload_csv.log 2>&1
  # csvファイルの削除を定期実行する
  delete_csv: 0 7 * * * find /home/pi/minelab-agri-platform/minelab-iot-gateway/csv -type f -name "*.csv" -delete