# Cronの設定情報
cron:
  # 画像を送信するスクリプトを定期実行する
  upload_image: 0 0 * * * python3 /home/pi/minelab-agri-platform/minelab-iot-gateway/upload_csv.py >> /home/pi/minelab-agri-platform/minelab-iot-gateway/log/upload_csv.log 2>&1