"parameters":
  # 観測するチャンネルを指定する
  "channel": 
  # 観測する帯域幅を指定する
  "bandwidth": 
  # フィルタリングするMACアドレスを指定する
  "mac": 

# 起動時に実行するコマンドを指定する
"commands":
  "mcp": sudo mcp -C 1 -N 1
  "ifconfig": sudo ifconfig wlan0 up
  "nexutil": sudo nexutil -Iwlan0 -s500 -b -l34 -v
  "iw": sudo iw dev wlan0 interface add mon0 type monitor
  "ip": sudo ip link set mon0 up

# Cronの設定情報
cron:
  # Pcapを取得するスクリプトを定期実行する
  get_pcap: */15 * * * * python3 /home/pi/minelab-agri-platform/minelab-iot-nexmon/get_pcap.py >> /home/pi/minelab-agri-platform/minelab-iot-nexmon/log/get_pcap.log 2>&1